name: render-draw-io-artifact-from-source-file
run-name: Rendering drawio image on ${{ format('{0:yyyy-MM-dd}', github.event.head_commit.timestamp) }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Convert test file to png image
        uses: Burnett01/actions-drawio@1.2
        with:
          src: 支米口罩产品简介.drawio
          dest: 支米口罩产品简介-${{github.event.head_commit.timestamp}}.png # add branch name
      - name: Upload image as artifact
        uses: actions/upload-artifact@v1
        with:
          name: png
          path: test.png
      # create release on push to main
